### ISSUE TITLE
Make AMD inputs a noop

### ISSUE THREAD

**Issue by rwjblue** [esperantojs/esperanto#104]
Currently, the following input:

```javascript
define('some-amd-file', ['exports'], function(exports) {
  exports.foo = 'foo!';
});
```

Generates:

```javascript
define(function () {

  'use strict';

  define('some-amd-file', ['exports'], function(exports) {
    exports.foo = 'foo!';
  });

});
```

---

It would be nice if we could opt-in to making processing already transpiled AMD (possibly other formats) files a no-op.

Thoughts?

**Comment by stefanpenner** [comment]
some fast auto-detection code could be handy

**Comment by eventualbuddha** [comment]
This would have to be only if you're targeting AMD, and only when not bundling. Could maybe be as simple as a regex: `/^\s*define\(.*\);?\s*$/`.

Then again, why are you passing non-ES6 code through esperanto?

**Comment by rwjblue** [comment]
The use-case:

In Ember CLI addons can return a tree of files. They *might* be ES6 or named-amd.  We would like to be able to just run them through the transpiler either way, and "do the right thing".

**Comment by stefanpenner** [comment]
@rwjblue it could also be one level up, the broccoli plugin that handles it via the regex above

**Comment by rwjblue** [comment]
Agreed.
