### ISSUE TITLE
Mixed default & named imports

### ISSUE THREAD

**Issue by ef4** [esperantojs/esperanto#111]
Esperanto currently supports:

    import { default as Foo, bar } from "my-module";

But the spec-compliant way to do this is:

    import Foo, { bar } from "my-module";

**Comment by rwjblue** [comment]
Looks like this is supported now.  Just tested in the live demo.

Input:

```javascript
import Foo, { blah } from 'bar';

new Foo();
blah + 1
```

Output:

```javascript
define(['bar'], function (bar) {

	'use strict';

	new bar['default']();
	bar.blah + 1

});
```

**Comment by eventualbuddha** [comment]
Closing since as far as I can tell this is working correctly.
