### ISSUE TITLE
Imports conflict with local variables

### ISSUE THREAD

**Issue by rlivsey** [esperantojs/esperanto#119]
I thought this might be the same / related to #95 or #116, but still happens in 0.6.17.

I have the following in my app:

```javascript
import {
  updateMeeting
} from 'minutebase/use-cases/meeting';

export function setupAgenda(meeting) {
  return updateMeeting(meeting);
};
```

Which is being transpiled to:

```javascript
define('minutebase/use-cases/agenda', ['exports', 'ember', 'minutebase/use-cases/meeting'], function (exports, Ember, meeting) {
  'use strict';

  exports.setupAgenda = setupAgenda;

  function setupAgenda(meeting) {
    return meeting.updateMeeting(meeting);
  }
});
```

Notice that there's an imported `meeting` and a local `meeting` which tramples on it so `meeting.updateMeeting` is `undefined`.

Should the imported name be mangled/prefixed in some way to lessen the chance of a collision?

**Comment by Rich-Harris** [comment]
@rlivsey Thanks for the test case, this is fixed in 0.6.23. Sorry for the delay
