### ISSUE TITLE
UMD with only CJS/AMD export

### ISSUE THREAD

**Issue by paulfalgout** [esperantojs/esperanto#126]
Sorry if this is a dupe, but I can't seem to find this elsewhere/

I would like to be able to generate the UMD wrap such that you can require the library into whatever
```js
var someWidget = require('widget');
```

But "widget" doesn't end up getting attached to `window` if loading via a `<script>` tag.

So essentially this:

```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require("someLibrary")) :
    typeof define === 'function' && define.amd ? define(["someLibrary"], factory) :
    factory(global.someLibrary)
  }
```

So that if loaded via `<script>` I can have `window.someLibrary.widget` with `window.widget` undefined, but not lose CJS/AMD exports.

**Comment by Rich-Harris** [comment]
Would this work? Bit of an undocumented hack but the `name` property used for UMD exports doesn't need to be a valid identifier:

```js
esperanto.toUmd({
  name: 'someLibrary.widget'
});

// or if it's a bundle
esperanto.bundle({
  base: 'src', // or whatever
  entry: 'main'
}).then( function ( bundle ) {
  var result = bundle.toUmd({
    name: 'someLibrary.widget'
  });
});
```

**Comment by paulfalgout** [comment]
Wow!  Yep that's all it took.  Thanks!

Should make that a documented hack :laughing:

**Comment by Rich-Harris** [comment]
Agree! Now documented https://github.com/esperantojs/esperanto/wiki/Converting-a-single-module#umd
