### ISSUE TITLE
change response to top-level `this`?

### ISSUE THREAD

**Issue by Rich-Harris** [esperantojs/esperanto#151]
Follow-on from https://github.com/artsyca/ember-cli-lodash/issues/3.

I'm happy with adding an `allowThis` option that simply replaces `this` with `undefined` rather than throwing an error on property access, but I'm unconvinced that we should only throw an error if someone has checked the `disallowThis` (or whatever) option. In the vast majority of cases, the use of `this.whatever` would be a misunderstanding on the part of the module author, and we have an opportunity to educate them and save them a good deal of frustration.

My suggestion: implement `allowThis` (any ideas for a more accurate name? `allowTopLevelThisPropertyAccess` possibly overkill), and change the error message to read 

```
`this` at the top level of an ES6 module is `undefined` - you cannot read or write its
properties. Use the `allowThis` option if you need to suppress this error
```

**Comment by jdalton** [comment]
I don't think it's esperanto's place to educate with default errors. Strict mode has been around for a while now and the behavior of `this` is nothing new. If anything a doc note on it would be fine. By doing this by default you catch valid JS. After all you don't know what kind of feature checks devs have in place.

**Comment by jdalton** [comment]
Ping. This is still [causing problems](https://github.com/truenorth/ember-lodash/commit/448c6d704691e59b6b41a2789e36471661767711#commitcomment-12008021).

**Comment by Rich-Harris** [comment]
Noted. Am tied up with a bunch of other stuff at the moment but if anyone out there wants to submit a PR...?

**Comment by jdalton** [comment]
I'm down for a PR. I'll try to get something working this evening. \cc @truenorth.

**Comment by truenorth** [comment]
Awesome. This would be lovely
