### ISSUE TITLE
Preserve sourceMaps?

### ISSUE THREAD

**Issue by clintwood** [esperantojs/esperanto#165]
In #35 there was a brief discussion of loss of accurate sourcemaps when using per-module pre-transforms.

In another scenario, given pre-transformed source (say via babel) that already has sourcemaps is there a way to preserve/augment these when transformed by esperanto (both as 1 to 1 and as bundles)?
e.g.:
```
es6 -> babel/traceur/etc. -> code + sourcemap -> esperanto -> CJS + sourcemap to original es6
```

**Comment by clintwood** [comment]
@Rich-Harris, hahaha, had a quick scout only to find you are the man on this... [sourcery.js](https://github.com/rich-harris/sorcery)

Would be good to have this feature in esperanto!

**Comment by Rich-Harris** [comment]
Closing as wontfix (#191)! Embedding Sorcery inside Esperanto/Rollup... I like the convenience of it, and there definitely is room for a tool that Just Works out-of-the-box, though I think of that as being something built on *top* of Babel/Rollup/Sorcery et al.
