### ISSUE TITLE
AVG detected a virus

### ISSUE THREAD

**Issue by Dan503** [esperantojs/esperanto#171]
I seriously doubt You guys put a virus in your code. You seem far too legit for that. When I had my monthly scan though it came back with this:

<img src="http://grabilla.com/05701-e062f3e4-6e68-43fb-a8e4-ff02488201b7.png" alt="virus found"/>

I thought you guys should know.

**Comment by Rich-Harris** [comment]
> You seem far too legit for that

You never know :) Though I've no idea what could have caused this – presumably AVG just being overzealous. Thanks for the heads-up, I'll have to close this as I don't have the first inkling how to go about 'fixing' it.
