### ISSUE TITLE
Make 'use strict' optional

### ISSUE THREAD

**Issue by Munawwar** [esperantojs/esperanto#172]
Hi. Could you make 'use strict' inside AMD module function optional (with a command line flag)?

**Comment by tdumitrescu** [comment]
+1

**Comment by Rich-Harris** [comment]
Hi – afraid I have to close this as `wontfix`, per #191. [Rollup](https://github.com/rollup/rollup) supports a `useStrict` option, and I've just raised an issue for CLI support (https://github.com/rollup/rollup/issues/81), and I believe Babel also allows you to exclude it.
