### ISSUE TITLE
export { default } from '...' causing parse error in IE8.

### ISSUE THREAD

**Issue by xcskier56** [esperantojs/esperanto#175]
This is an issue in ember-wormhole, and liquid-fire. When directly exporting a component with `export { default } from 'somewhere/component-name'` It outputs `exports.default = component-name.default;` which causes a parse error in IE8. 

The [current solution](https://github.com/ef4/liquid-fire/issues/311) courtesy of @rwjblue is found

    // change 
    export { default, measure } from "liquid-fire/components/liquid-measured";
    // which outputs:
    exports.default = liquid_measured.default; // IE8 Parse Error
    exports.measure = liquid_measured.measure;

    // to 
    import LiquidMeasured, { measure } from 'liquid-fire/components/liquid-measured';

    export default LiquidMeasured;
    export { measure };
    // which outputs 
    exports['default'] = liquid_measured['default'] // works in IE8.
    exports.measure = liquid_measured.measure;

@stefanpenner suggested in a [PR](https://github.com/yapplabs/ember-wormhole/pull/17) that this was a issue with esperanto and to report here.

**Comment by eventualbuddha** [comment]
The current version seems to output as you expect. What version of esperanto are you using? Perhaps you need to update?

**Comment by stefanpenner** [comment]
ember-cli has a `^0.7.2` dep, so it should drift up correctly -> https://github.com/ember-cli/broccoli-es6modules/blob/master/package.json#L15

**Comment by XrXr** [comment]
@eventualbuddha I just tried with 0.7.3

```js
var es = require('esperanto')

console.log(es.toCjs("export { default} from 'foo';",  {
  strict: true,
  _evilES3SafeReExports: true
}).code);
```

outputs 

```js
'use strict';

var foo = require('foo');

exports.default = foo.default;
```

Which version works?

**Comment by stefanpenner** [comment]
> 'use strict';
> 
> var foo = require('foo');
> 
> exports.default = foo.default;

this doesn't look like AMD

**Comment by XrXr** [comment]
@stefanpenner my mistake. Should of called `.toAmd()`

```js
var es = require('esperanto')

console.log(es.toAmd("export { default} from 'foo';",  {
  strict: true,
  _evilES3SafeReExports: true
}).code);
```

```js
define(['exports', 'foo'], function (exports, foo) {

	'use strict';



	exports.default = foo.default;

});
```

**Comment by XrXr** [comment]
@eventualbuddha  I dug into it a bit more and came up with a PR for it :) #176
