### ISSUE TITLE
make Esperanto easier to find

### ISSUE THREAD

**Issue by iambumblehead** [esperantojs/esperanto#177]
I'm not the best person to offer a solution for this but am letting you know Esperanto is hard to find.

I searched for hours looking for a tool like Esperanto. I looked at sources found in various repositories that didn't comprehensively solve my problem -things like umd, urequire, browser-pack, es6-module-transpiler etc.

Esperanto is the solution, but its hard to find. I came to it from this ycombinator page https://news.ycombinator.com/item?id=8197988

**Comment by Rich-Harris** [comment]
Agree! It's a well-kept secret. Not sure what the solution is - the [website](http://esperantojs.org/) could probably be better, but I guess ultimately it's just a question of 'marketing', which I'm terrible at.

Having said that - and you probably don't want to hear this, having spent all that time trying to track down a solution - I'm curently working on a *different* ES6 module bundler called [Rollup](https://github.com/rollup/rollup), which will eventually supersede Esperanto (or at least Esperanto's bundling logic will be replaced with Rollup internally). So whatever slim mindshare Esperanto has built up will become less relevant...

**Comment by Rich-Harris** [comment]
closing in favour of https://github.com/rollup/rollup/issues/67!
