### ISSUE TITLE
Support relative sourcemaps in the CLI

### ISSUE THREAD

**Issue by patrickarlt** [esperantojs/esperanto#178]
```js
esperanto -i src/EsriLeaflet.js -o dist/esri-leaflet-src.js --skip=leaflet -t umd --strict --name L.esri --bundle -m esri-leaflet-src.js.map
```

Produces a sourcemap with:

```js
//# sourceMappingURL=/Users/patricklocal/code/esri-leaflet/dist/esri-leaflet-src.js.map
```

This is a really useful feature from browserify/exorcist since it makes it possible to distribute the sourcemaps next to the compiled files for use over a CDN or as a download.

**Comment by Rich-Harris** [comment]
Closing – see response to #179
