### ISSUE TITLE
Comments after imports incorrectly stripped

### ISSUE THREAD

**Issue by sparhami** [esperantojs/esperanto#187]
Any comments present in a file after an import statement, but before the first expression in that file are incorrectly removed by esperanto. The following example reproduces the issue in v0.7.4:

In entry.js:
```javascript
import { number } from './number.js';

/** A comment for obj */
var obj = {};

export {
  obj
};
```

In number.js:
```javascript
/** A comment for a number */
var number = 5;

export {
  number
};
```

Command run:
```
esperanto -i entry.js -b -s
```

The output is as follows. Note the missing comment before `var obj = {};`:
```javascript
define(['exports'], function (exports) {

  'use strict';

  /** A comment for a number */
  var number = 5;

  var obj = {};

  exports.obj = obj;

});
```

**Comment by Rich-Harris** [comment]
Apologies for the slow response. You probably don't want to hear this so soon after switching to Esperanto, but I'm [in the process of abandoning this project](https://github.com/esperantojs/esperanto/pull/191)!

The good news is three-fold: 

1. [Rollup](https://github.com/rollup/rollup) will take over from Esperanto
2. It looks like incremental-dom builds just fine with Rollup
3. Rollup doesn't have this bug

I'll close this issue, and submit a PR to incremental-dom momentarily
