### ISSUE TITLE
Is there a method to pass input source maps to esperanto?

### ISSUE THREAD

**Issue by calebmer** [esperantojs/esperanto#190]
When using the `modules` property in `esperanto.bundle` is there a way to also pass in source maps? For example:
```
esperanto.bundle({
  ...
  modules: {
    'index.js': {
      code: '...',
      ast: {...},
      map: {...}
    }
  }
}).then( ... );
```

**Comment by Rich-Harris** [comment]
Unfortunately not. I've found it adds a lot of complexity for each step in a build pipeline to have to worry about incoming sourcemaps – I created a tool called [sorcery](https://github.com/rich-harris/sorcery) to help with this scenario. It will take any output file and flatten a chain of sourcemaps into one.
