### ISSUE TITLE
Add deprecation notice to repo description

### ISSUE THREAD

**Issue by jmeas** [esperantojs/esperanto#192]
Maybe? I usually do just to be completely sure that people see the notice.

p.s. I mean this description:

<img width="632" alt="screen shot 2015-08-24 at 5 54 09 pm" src="https://cloud.githubusercontent.com/assets/2322305/9453562/251b39e4-4a89-11e5-98a1-8f3fb4faf867.png">

**Comment by eventualbuddha** [comment]
Done.
