### ISSUE TITLE
SystemJS support

### ISSUE THREAD

**Issue by sebmck** [esperantojs/esperanto#53]
Currently esperanto can't compile to SystemJS. It's the only module loader that supports circular dependencies, live bindings etc. Without these it's impossible to replicate ES6 modules exactly.

Reference: https://github.com/ModuleLoader/es6-module-loader/wiki/System.register-Explained

**Comment by Rich-Harris** [comment]
Thanks for the link. I hadn't really looked into it - in my head SystemJS was kinda like AMD except with `System.register` instead of `define`...

Agree that it would be worth supporting.

**Comment by eventualbuddha** [comment]
As mentioned in #51 a bundle of ES6 modules can also support ES6 module spec fully. That said, SystemJS would be good to support.

**Comment by Rich-Harris** [comment]
Closing this in favour of https://github.com/rollup/rollup/issues/83, as I'm planning to abandon Esperanto in favour of Rollup. For one-to-one transformations I'm recommending people use Babel
