### ISSUE TITLE
Report external modules

### ISSUE THREAD

**Issue by Rich-Harris** [esperantojs/esperanto#59]
See https://github.com/ef4/broccoli-es6modules/pull/4#issuecomment-69940889. It would be useful to report which external modules are required by a bundle. Something like

```js
esperanto.bundle( bundleOptions ).then( function ( bundle ) {
  console.log( 'external dependencies: ' + bundle.external.join( ', ' ) );
  doSomethingWith( bundle.external );
  fs.writeFileSync( 'bundle.js', bundle.toAmd(...) );
});
```

**Comment by stefanpenner** [comment]
with petal i have the following format:

```js
bundle.exports = {
  moduleName: [ 'export1', 'export2']
}

bundle.imports = {
  moduleName: [ 'import1', 'import2']
}
```

(the reason for the toplevel name in my case, is that it supports bundles of modules in the same file, which may not be needed for this project)

**Comment by stefanpenner** [comment]
no pressure, just planning some stuff. Do you have an ETA for this?

**Comment by Rich-Harris** [comment]
Just submitted #61. Behaves as described as above, that should work for https://github.com/ef4/broccoli-es6modules/pull/4, right?

/cc @ef4

**Comment by eventualbuddha** [comment]
I think it would be useful to have an option that would allow consumers of esperanto to resolve external modules for it. Maybe something like this API?

```js
// find npm packages
const resolve = require('resolve');
const dirname = require('path').dirname;

esperanto.bundle({
  // better names for these…?
  resolveExternal(externalPath, resolvingPath) {
    return new Promise((accept, reject) => {
      resolve(externalPath, { basedir: dirname(resolvingPath) }, (err, resolvedPath) => {
        if (err) reject(err);
        else accept(resolvedPath);
      });
    });
  }
})
```

**Comment by stefanpenner** [comment]
> I think it would be useful to have an option that would allow consumers of esperanto to resolve external modules for it. Maybe something like this API?

that would be gret.

**Comment by caridy** [comment]
Yeah, that API is required to support npm packages that contains ES6 modules, similar to what we do today with `es6-module-transpiler-npm-resolver` to resolve the main entry of a library by using `jsnext:main` directive from package.json, here is the current resolver: https://github.com/caridy/es6-module-transpiler-npm-resolver/blob/master/index.js

**Comment by caridy** [comment]
As for the API of the external resolver, there are two main use-cases:

1. resolve a filepath (e.g.: resolving jsnext:main from package.json that resolves to a fullpath)
1. resolve a synthatic module in a form of a string value (e.g.: a shim for global value or any other runtime value)

Keep in mind that 2) is not very common, it is proven to be a flexible solution when producing bundles.

**Comment by Rich-Harris** [comment]
Released 0.6.5 with this feature (and opened #68 to continue discussion about path resolution)

**Comment by caridy** [comment]
@Rich-Harris what exactly was released? I could not find the details in the release notes.

**Comment by rwjblue** [comment]
@caridy - https://github.com/esperantojs/esperanto/wiki/Bundling-multiple-ES6-modules#getting-information-about-the-bundle
