### ISSUE TITLE
Minor tweak to import syntax?

### ISSUE THREAD

**Issue by dbashford** [esperantojs/esperanto#6]
Consider transpiling to this?

```javascript
define(['ember','exports'],function (__imports_0, exports) {
  var Ember = __imports_0.default || __imports_0;
```

Note the `|| __imports_0`.  While our own modules will have a `default`, vendor libraries will not.

**Comment by Rich-Harris** [comment]
Coming up on the anniversary of this issue :grimacing: Closing as wontfix, per #191 – Babel (for one-to-one transformations) and Rollup (for bundles) are both more forgiving when it comes to this sort of interoperability, and don't insist on symmetry between import/export type like Esperanto does.
