### ISSUE TITLE
Handle multiple imports from the same file.

### ISSUE THREAD

**Issue by rwjblue** [esperantojs/esperanto#63]
Currently, the following:

```javascript
import foo from "foo";
import { bar } from "foo";

foo.stuff();
bar.otherStuff()
```

Will result in the following output (using single module + strict mode):

```javascript
define(['foo', 'foo'], function (foo, foo) {

	'use strict';

	foo['default'].stuff();
	foo.bar.otherStuff()

});
```

This throws an error as we have two function arguments with the same name.

**Comment by Rich-Harris** [comment]
Ah, of course - didn't catch this when I looked into it before because it doesn't affect bundles. Should be an easy fix
