### ISSUE TITLE
Concat shouldn't care about external imports

### ISSUE THREAD

**Issue by lukescott** [esperantojs/esperanto#64]
I'm exporting a single module with several internal modules. I use lodash as an external import. I use 6to5 to transpile the source after esperanto bundles the modules. The result with umd ends up being something like this:

```javascript
(function() { // <-- Added by me to keep runtime internal
"use strict"; // <-- Added by 6to5
// ES6 runtime goes here...
(function(global, factory) {
// umd code..
}(this, function(_) { // <-- this does not work because of above strict
"use strict";
// actual code...
});
}); // <-- Added by me to keep runtime internal
```

What I want to do is this:

```javascript
(function() { <-- Added by me
"use strict";
// ES6 runtime goes here...
// actual code...
return index__default; // <-- Added by me
}); // <-- Added by me
```

The concat option would work great for this, accept for this:

```javascript
// This bundle must be self-contained - no imports or exports
if ( bundle.externalModules.length || bundle.entryModule.exports.length ) {
	throw new Error( 'bundle.concat() can only be used with bundles that have no imports/exports' );
}
```

In this case I know what my external dependencies are, and I'm willing to take care of them myself. I just need a way to bypass that error (which for some reason bailed without any message in gulp...).

**Comment by Rich-Harris** [comment]
The short-term workaround is to use the `skip` option:

```js
esperanto.bundle({
  base: 'src',
  entry: 'app',
  skip: [ 'lodash' ]
}).then( function ( bundle ) {
  fs.writeFile( 'bundle.js', bundle.concat() );
});
```

That way, it won't look for `lodash`, and as a result won't treat it as an external dependency.

A longer term solution would be to provide more flexibility in how bundles are constructed. There's an `intro` and `outro` option - currently undocumented and untested - that [aims to help in this regard](https://github.com/esperantojs/esperanto/blob/master/src/bundler/builders/concat.js#L14-L15):

```js
esperanto.bundle( options ).then( function ( bundle ) {
  fs.writeFile( 'bundle.js', bundle.concat({
    intro: '(function () { // my custom intro \n',
    outro: '\n})(); // my custom outro'
  }) );
});
```

Conceivably, `intro` could be changed to optionally be a function that gets called with e.g an array of external dependencies. Will add an enhancement label to this issue. There may be some complexity around ES5-6 interoperability, I'm not sure yet.

As an aside, I've found that I get quicker builds if I run 6to5 *before* esperanto - 6to5 seems to be much quicker at transpiling 10 100-line files than 1 1000-line one. I use the `blacklist` option to prevent 6to5 converting modules and adding 'use strict' (`blacklist: ['modules', 'useStrict']`).

**Comment by lukescott** [comment]
@Rich-Harris, thanks for the tips! I'm using gulp-6to5 and the bundle feature of esperanto. If I do the 6to5 conversion first, how do I feed the file stream into esperanto's bundler? This is what my task currently looks like:

```javascript
function esperantoBundle(options) {
	var name = options.name;
	if (name.substr(-3) !== ".js") {
		name += ".js";
	}
	var stream = through.obj();
	esperanto.bundle(options).then(function(bundle) {
		var b = bundle.concat(options);
		var code = b.code;
		var file = new gutil.File({
			path: name,
			contents: new Buffer(code)
		});
		stream.push(file);
	});
	return stream;
}

esperantoBundle({
	base: "./app",
	entry: "index",
	name: "appname",
	intro: "",
	outro: "\nglobal.appname = index__default;",
	ignoreExternal: true
})
.pipe(to5({
	loose: ["forOf"]
}))
.pipe(wrap(
	"(function(global){\n<%= contents %>})(this)"
))
.pipe(gulp.dest("dist"));
```

What I like about this is the requires are removed completely. Since I don't have any circular dependencies, this works out well. The downside is that when using `for(let item of items)` the vars generated to 6to5 use a counter for the whole file. So if I add a new iterator somewhere it changes half the iterators in the file, resulting in a change-set much larger than the original for dist. I would imagine that if I could do the same thing with 6to5 transforming individual files, the counter would be local to the file, and reduce the noise.

**Comment by lukescott** [comment]
The skip option is failing with concat. It also fails silently, so no error is showing up.

**Comment by Rich-Harris** [comment]
Hmm. That's odd - it worked for me over the weekend. Will look into it

**Comment by lukescott** [comment]
Skip works now. It just complains about the single export now. Just need to wrapper to fix that though.
