### ISSUE TITLE
Documentation needs an update

### ISSUE THREAD

**Issue by lukescott** [esperantojs/esperanto#65]
I'm not that familiar with each and every option, but I did notice that the [bundle guide]( https://github.com/esperantojs/esperanto/wiki/Bundling-multiple-ES6-modules) seem to be out of date, specifically this example:

```javascript
esperanto.bundle({
  base: 'src', // optional, defaults to current dir
  entry: 'mean.js' // the '.js' is optional
}).then( function ( bundle ) {
  fs.writeFile( 'dist/mean.js', bundle.toCjs() );
});
```

It would seem that the writeFile line should be:

```javascript
  fs.writeFile( 'dist/mean.js', bundle.toCjs().code );
```

Also, not all the options are documented, or at least I haven't been able to find them, such as `skip`.

**Comment by Rich-Harris** [comment]
Thanks, you're right, the docs were a bit dusty. I *think* they're up to date now, so I'll close this issue, but let me know if you spot any others!
