### ISSUE TITLE
Cache analysis/ast for incremental builds

### ISSUE THREAD

**Issue by Rich-Harris** [esperantojs/esperanto#72]
Incremental bundle builds (e.g. using [gobble-esperanto-bundle](https://github.com/gobblejs/gobble-esperanto-bundle)) could be a good deal quicker if the analysis and AST were cached somehow.

This could be e.g. a `.esperanto-cache.json` map of checksums to modules. On reading a file, if we found that a generated checksum matched one already in our cache, we just `JSON.parse()` the existing representation, rather than running the file through acorn and the subsequent AST annotation etc to generate a new one.

There'd likely be some hoops to jump through to serialise the internal representation of a module, since it's not composed entirely of POJOs (e.g. the `Scope` objects the AST is annotated with), and there are probably some circular references and so on. But I would expect the trade-off to be well worth it.

**Comment by rwjblue** [comment]
This could also be very useful for ember and ember-cli (from Broccoli).

**Comment by Rich-Harris** [comment]
Closing in favour of https://github.com/rollup/rollup/issues/2
