### ISSUE TITLE
Named exports that are functions can be elevated incorrectly.

### ISSUE THREAD

**Issue by rwjblue** [esperantojs/esperanto#73]
The following input:

```javascript
var foo = "bar";

if (false) {
  someFunction = function foo() {  };
}

export {
 foo 
}
```

Results in:

```javascript
define(['exports'], function (exports) {

  'use strict';

  exports.foo = foo;

  var foo = "bar";

  if (false) {
    var someFunction = function foo() {  };
  }

});
```

---

It seems that since a function named `foo` existed (even though it was not available as `foo` since it was assigned to `someFunction` variable) the transpiler assumed that it could hoist the named export to the beginning of the file.  In this case, it results in `exports.foo` being `undefined` when later required by other modules.

**Comment by rwjblue** [comment]
For a less contrived example, see the following code in Ember:

* `defineProperty` [variable here](https://github.com/emberjs/ember.js/blob/d2d1490d0d4e09a5ec7a8ce916f6ed287bef8d65/packages/ember-metal/lib/platform/define_property.js#L26)
* `defineProperty` [function polyfill here](https://github.com/emberjs/ember.js/blob/d2d1490d0d4e09a5ec7a8ce916f6ed287bef8d65/packages/ember-metal/lib/platform/define_property.js#L124-L126)

The resulting named export of `defineProperty` is `undefined` (since there was no function available but the `exports.defineProperty = defineProperty;` was hoisted to the beginning of the AMD module).

**Comment by rwjblue** [comment]
Another example:

```javascript
var foo = function foo() { }

export {
 foo 
}
```

```javascript
define(['exports'], function (exports) {

	'use strict';

	exports.foo = foo;

	var foo = function foo() { }

});
```

It is obvious that `var foo = function foo() { }` doesn't make sense, but it would be nice if the transpilation step didn't cause this failure.

**Comment by Rich-Harris** [comment]
I have this fixed locally - am on a plane with crappy WiFi, will push later
