### ISSUE TITLE
AMD callback name selection prevents usage of local variables with same name.

### ISSUE THREAD

**Issue by rwjblue** [esperantojs/esperanto#74]
Input:

```javascript
var exports = {};

export default exports;
```

Output:

```javascript
define(['exports'], function (exports) {

	'use strict';

	var exports = {};

	exports['default'] = exports;

});
```

---

The callback arguments should not use a name that conflicts with variables in the local scope.

**Comment by Rich-Harris** [comment]
Have a fix, will push when I have good wifi

**Comment by eventualbuddha** [comment]
Oh no! I also have a fix. That's why I assigned to myself. I'll push mine anyway so we can compare approaches.

**Comment by Rich-Harris** [comment]
Ah, didn't know - got the issue email just before take off! Am sure our
fixes are very similar, so by all means merge yours - I'll be AFK for a
while
