### ISSUE TITLE
Enable Automated CI?

### ISSUE THREAD

**Issue by rwjblue** [esperantojs/esperanto#78]
It would be great to see this repo running tests automatically on PR's and whatnot for supported platforms.

The ember-cli ecosystem is slowly migrating towards using:

* Travis - Normal linux based CI (running against node v0.10, node v0.11, and hopefully soon io.js).
* AppVeyor - Windows based CI (to help assure us that our tooling works properly under Windows). Since Windows CI can be frustrating, it may make sense to skip it initially and circle back to it later...

**Comment by eventualbuddha** [comment]
Yep, good suggestion. Travis was added by a7f9ed1d34a17d3f5e6ee62168dc40842ffe3cef. Working on Appveyor.

**Comment by eventualbuddha** [comment]
This is now set up.

**Comment by rwjblue** [comment]
Awesome!

**Comment by eventualbuddha** [comment]
@rwjblue I'm having some trouble getting Appveyor to work. I replaced the `build.sh` script on a branch with a `build.js` file meant to run against node, but it does not seem to be working. Any insight you can share?

https://ci.appveyor.com/project/eventualbuddha/esperanto/build/job/mt7kmx3wy4esd5uu

**Comment by rwjblue** [comment]
Pinging @raytiley (he setup and got ember-cli to work properly on AppVeyor).
