### ISSUE TITLE
AMD callback dependency names shadow globally-defined variables

### ISSUE THREAD

**Issue by brzpegasus** [esperantojs/esperanto#79]
I looked through the issue list and saw several that deal with variable shadowing, but there's still a case that doesn't seem to be addressed yet.

This ES6 module:
```javascript
import { find } from './mod/path/location';
find();
console.log(location.href);
```

transpiles to:
```javascript
define(['./mod/path/location'], function (location) {
	'use strict';

	location.find();
	console.log(location.href);
});
```

So within the scope of this function callback, the `location` from `window.location` has been shadowed by the module dependency name. The current functionality only seems to rename the dependency as `path__location` if the name `location` was redefined inside the callback:

```javascript
import { find } from './mod/path/location';
var location = '';
find();
console.log(location.href);
```

now becomes:

```javascript
define(['./mod/path/location'], function (path__location) {
	'use strict';

	var location = '';
	path__location.find();
	console.log(location.href);
});
```

This issue happened in an Ember app, where we had a module called `helpers/click` with a bunch of click helper functions:

```javascript
import { clickLink } from './helpers/click';

clickLink('some link');
click('.foo'); // Ember-defined click helper, which gets injected onto the global namespace
```

When this transpiles to AMD, the `click` helper that Ember made available globally is no longer available (unless you specifically call `window.click` instead of just `click`).

**Comment by rwjblue** [comment]
@brzpegasus - Thank you for the reproduction! Not sure the best way forward here, unless it is to use es6-module-transpiler semantics (or enable them to via an option) of using something like `__dependency1__, __dependency2__` etc.

@eventualbuddha / @Rich-Harris - Thoughts?

**Comment by eventualbuddha** [comment]
My approach would be to collect all the unbound references (globals) and disallow them as generated names.

**Comment by Rich-Harris** [comment]
I was going to suggest using deconflicting against [this list](https://github.com/esperantojs/esperanto/blob/master/src/utils/builtins.js), but actually I think @eventualbuddha's is the right idea. I can't remember if we already collect that information (undeclared refs) somewhere

**Comment by rwjblue** [comment]
IMHO, checking against a static list is unlikely to do the trick. In the case reported, a `click` function is created at runtime of the application. `click` is just one example, almost anything could have the same issue (what if you `import { blah } from 'utils/window';`? it would override the global `window`...).

I'm unsure how the undeclared refs could be built dynamically, at least in the Ember and ember-cli case, since these modules will be generated in node but used in a browser context.

**Comment by rwjblue** [comment]
I think I misunderstood what @eventualbuddha was saying. If I understand correctly now, his approach would mean that any references in the file being transpiled that were not declared/created in that file would be assumed to be globals and be blacklisted for callback function argument names.

**Comment by Rich-Harris** [comment]
I think the idea is to traverse the AST and find any names that aren't in scope - there's already a [getUnscopedNames](https://github.com/esperantojs/esperanto/blob/master/src/bundler/combine/getUnscopedNames.js) function that @leebyron added, I imagine it's just a case of using that and ensuring that generated module names don't conflict. It should catch `click`

**Comment by Rich-Harris** [comment]
Ah, jinx! Yep, we're on the same page I think

**Comment by rwjblue** [comment]
@Rich-Harris - Thanks, sorry for the initial confusion!

**Comment by Rich-Harris** [comment]
no worries! will jump on this shortly, and try and get a new release out this evening

**Comment by leebyron** [comment]
Sounds like a great way to reuse the result of `getUnscopedNames` - that's exactly it's purpose.

**Comment by brzpegasus** [comment]
Thanks for the quick fix! I verified this is now working as expected on 0.6.6.
