### ISSUE TITLE
mixing esperanto and 6to5 leads to quirks

### ISSUE THREAD

**Issue by stefanpenner** [esperantojs/esperanto#86]
* esperanto for modules
* 6to5 for everything else

given

```js
export default class Foo() {

}
```

we get

```js
export default var Foo = (...);
```

which clearly isn't correct.

**Comment by eventualbuddha** [comment]
Can you be more specific? What order are you running them in? What options, specifically whitelist/blacklist for 6to5 and bundle on/off & module format for esperanto?

**Comment by eventualbuddha** [comment]
Also, is something changing the case of `Foo` or is that a mistake in the example?

**Comment by stefanpenner** [comment]
1. 6to5 with modules off
2. named AMD output of esperanto

**Comment by stefanpenner** [comment]
> Also, is something changing the case of Foo or is that a mistake in the example?

typo

**Comment by stefanpenner** [comment]
let me know if further clarification is needed

**Comment by sebmck** [comment]
@stefanpenner 6to5 issue, it's been fixed in 3.0.0. 6to5 shouldn't be outputting variable declarations inside of `export default` when modules is blacklisted.

**Comment by stefanpenner** [comment]
ah, what is the new output?

**Comment by sebmck** [comment]
```javascript
"use strict";

var Foo = function Foo() {};

export default Foo
```

**Comment by stefanpenner** [comment]
thanks

**Comment by stefanpenner** [comment]
3.0 of 6to5 should be out tonight.

**Comment by thejameskyle** [comment]
released
