### ISSUE TITLE
Simpler UMD

### ISSUE THREAD

**Issue by thejameskyle** [esperantojs/esperanto#91]
AMD should be first because some amd environments have a global `exports` object 

```js
typeof define === 'function' && define.amd ? define(['lodash'], factory) :
typeof exports === 'object' ? module.exports = factory(require('lodash')) :
global.Foo = factory(global._)
```

**Comment by Rich-Harris** [comment]
Ha... see #42, particularly [this comment](https://github.com/esperantojs/esperanto/pull/42#issuecomment-69287553). We went *away* from AMD-first (following browserify's lead) because it was causing different problems.

Can you outline the scenario in more detail?

**Comment by thejameskyle** [comment]
Heh, it's been a while since I actually looked into it. I believe it had to do with some setups implementing both the synchronous "Common.js" spec and the asynchronous "AMD" spec.

**Comment by thejameskyle** [comment]
Closing this as part of cleaning out old issues. Feel free to reopen this.
